# This file defines the sensors that are connected to the robot.
cameras:
    rgbd: 
        name: realsense_d435i
        quantity: 1
        pan: 0
        tilt: 0
        tf_frames: 
            - camera_link_0
        
    tof:
        name: vl53l8cx
        quantity: 2
        pan: 0 # for now, we assume that the TOF sensors are mounted on the same plane as defined by the URDF. Change if needed.
        tilt: 0
        tf_frames: 
            - tof_link_0
            - tof_link_1
        
    
    
    