# This file defines the sensors that are connected to the robot.
cameras:
    rgbd: 
        type: realsense_d435i
        quantity: 1
        
    tof:
        type: vl6180
        quantity: 2
        
    
    
    